"""
Costanti, categorie e regex precompilate per FCI_PROJECT.

Questo modulo contiene:
- Regex precompilate per parsing e normalizzazione
- Categorie Food & Beverage e Spese Generali
- Dizionario correzioni intelligente per classificazione
- Lista fornitori Spese Generali
- Colori per grafici Plotly

Tutte le regex sono precompilate all'avvio per ottimizzazione performance.
"""
import re


# ============================================================
# REGEX PRECOMPILATE (OTTIMIZZAZIONE PERFORMANCE)
# ============================================================
# Compilate una volta sola all'avvio, riutilizzate migliaia di volte

# Normalizzazione descrizioni
REGEX_UNITA_MISURA = [
    re.compile(r'\bKG\b', re.IGNORECASE),
    re.compile(r'\bG\b', re.IGNORECASE),
    re.compile(r'\bGR\b', re.IGNORECASE),
    re.compile(r'\bGRAMMI\b', re.IGNORECASE),
    re.compile(r'\bL\b', re.IGNORECASE),
    re.compile(r'\bLT\b', re.IGNORECASE),
    re.compile(r'\bLITRI\b', re.IGNORECASE),
    re.compile(r'\bML\b', re.IGNORECASE),
    re.compile(r'\bPZ\b', re.IGNORECASE),
    re.compile(r'\bPZZ\b', re.IGNORECASE),
    re.compile(r'\bPEZZI\b', re.IGNORECASE),
    re.compile(r'\bPEZZO\b', re.IGNORECASE),
    re.compile(r'\bCF\b', re.IGNORECASE),
    re.compile(r'\bCONF\b', re.IGNORECASE),
    re.compile(r'\bCONFEZIONE\b', re.IGNORECASE),
    re.compile(r'\bNR\b', re.IGNORECASE),
    re.compile(r'\bNÂ°\b', re.IGNORECASE),
    re.compile(r'\bNUMERO\b', re.IGNORECASE),
    re.compile(r'\bCT\b', re.IGNORECASE),
    re.compile(r'\bCTN\b', re.IGNORECASE),
    re.compile(r'\bCARTONE\b', re.IGNORECASE),
    re.compile(r'\bSCAT\b', re.IGNORECASE),
    re.compile(r'\bSCATOLA\b', re.IGNORECASE),
    re.compile(r'\bBAR\b', re.IGNORECASE),
    re.compile(r'\bBARATTOLO\b', re.IGNORECASE),
    re.compile(r'\bBUST\b', re.IGNORECASE),
    re.compile(r'\bBUSTA\b', re.IGNORECASE),
    re.compile(r'\bVAS\b', re.IGNORECASE),
    re.compile(r'\bVASETTO\b', re.IGNORECASE)
]

REGEX_NUMERI_UNITA = re.compile(r'\b\d+[.,]?\d*\s*(?:KG|G|L|ML|PZ|%|EUR|â‚¬)?\b', re.IGNORECASE)

REGEX_SOSTITUZIONI = {
    re.compile(r'\bINT\.?\b', re.IGNORECASE): 'INTERO',
    re.compile(r'\bCONF\.?\b', re.IGNORECASE): 'CONFEZIONE',
    re.compile(r'\bPZ\.?\b', re.IGNORECASE): 'PEZZO',
    re.compile(r'\bBOT\.?\b', re.IGNORECASE): 'BOTTIGLIA',
    re.compile(r'\bLAT\.?\b', re.IGNORECASE): 'LATTINA',
    re.compile(r'\bVAS\.?\b', re.IGNORECASE): 'VASETTO',
    re.compile(r'\bBAR\.?\b', re.IGNORECASE): 'BARATTOLO',
    re.compile(r'\bFR\.?\b', re.IGNORECASE): 'FRESCO',
    re.compile(r'\bFRESC\.?\b', re.IGNORECASE): 'FRESCO',
    re.compile(r'\bSURG\.?\b', re.IGNORECASE): 'SURGELATO',
    re.compile(r'\bBIO\.?\b', re.IGNORECASE): 'BIOLOGICO',
    re.compile(r'\bS\.?\s*GLUT\.?\b', re.IGNORECASE): 'SENZA GLUTINE',
    re.compile(r'\bS\.?\s*LATT\.?\b', re.IGNORECASE): 'SENZA LATTOSIO'
}

REGEX_PUNTEGGIATURA = re.compile(r'[.,;:\-_/\\]+')

REGEX_ARTICOLI = [
    re.compile(r'\bIL\b', re.IGNORECASE),
    re.compile(r'\bLO\b', re.IGNORECASE),
    re.compile(r'\bLA\b', re.IGNORECASE),
    re.compile(r'\bI\b', re.IGNORECASE),
    re.compile(r'\bGLI\b', re.IGNORECASE),
    re.compile(r'\bLE\b', re.IGNORECASE),
    re.compile(r'\bUN\b', re.IGNORECASE),
    re.compile(r'\bUNA\b', re.IGNORECASE),
    re.compile(r'\bDI\b', re.IGNORECASE),
    re.compile(r'\bDA\b', re.IGNORECASE)
]

# Dicitura vs prodotto
REGEX_LETTERE_MINIME = re.compile(r'[A-Za-z]{3,}')
REGEX_PATTERN_BOLLA = re.compile(r'^[A-Z\s]{3,15}\sDEL\s\d{2}[-/]\d{2}[-/]\d{4}')

# Estrazione peso dalla descrizione
REGEX_KG_NUMERO = re.compile(r'KG\s*(\d+[.,]?\d*)', re.IGNORECASE)
REGEX_GR_NUMERO = re.compile(r'GR\s*(\d+)', re.IGNORECASE)
REGEX_ML_NUMERO = re.compile(r'ML\s*(\d+)', re.IGNORECASE)
REGEX_CL_NUMERO = re.compile(r'CL\s*(\d+)', re.IGNORECASE)
REGEX_LT_NUMERO = re.compile(r'L(?:T)?\s*(\d+[.,]?\d*)', re.IGNORECASE)
REGEX_PZ_NUMERO = re.compile(r'PZ\s*(\d+)', re.IGNORECASE)
REGEX_X_NUMERO = re.compile(r'X\s*(\d+)', re.IGNORECASE)
REGEX_PARENTESI_NUMERO = re.compile(r'\((\d+)\)')
REGEX_NUMERO_KG = re.compile(r'(\d+[.,]?\d*)\s*KG', re.IGNORECASE)
REGEX_NUMERO_LT = re.compile(r'(\d+[.,]?\d*)\s*(?:LT|LITRI)', re.IGNORECASE)
REGEX_NUMERO_GR = re.compile(r'(\d+)\s*(?:GR|GRAMMI)', re.IGNORECASE)

# Pulizia testo
REGEX_PUNTEGGIATURA_FINALE = re.compile(r'[.,;:!?]+$')


# ============================================================
# COLORI GRAFICI PLOTLY
# ============================================================
COLORI_PLOTLY = [
    "#636EFA", "#EF553B", "#00CC96", "#AB63FA", "#FFA15A",
    "#19D3F3", "#FF6692", "#B6E880", "#FF97FF", "#FECB52"
]


# ============================================
# CATEGORIE FOOD & BEVERAGE (prodotti vendibili)
# ============================================
CATEGORIE_FOOD_BEVERAGE = [
    "CARNE", "PESCE", "LATTICINI", "SALUMI", "UOVA", "SCATOLAME E CONSERVE",
    "OLIO E CONDIMENTI", "SECCO", "VERDURE", "FRUTTA", "SALSE E CREME",
    "ACQUA", "BEVANDE", "CAFFE E THE", "BIRRE", "VINI",
    "VARIE BAR", "DISTILLATI", "AMARI/LIQUORI", "PASTICCERIA",
    "PRODOTTI DA FORNO", "SPEZIE E AROMI", "GELATI", "SHOP", "SUSHI VARIE"
]


# ============================================
# CATEGORIE MATERIALI E CONSUMABILI (F&B!)
# ============================================
# IMPORTANTE: MATERIALE DI CONSUMO Ãˆ CONSIDERATO F&B!
# Contiene materiali di consumo per il ristorante:
# - Tovaglioli, piatti/bicchieri usa e getta
# - Pellicole, contenitori asporto, buste
# - Detergenti per stoviglie, spugne
# - Guanti, cannucce, posate monouso
# Questi prodotti DEVONO apparire negli alert/sconti
CATEGORIE_MATERIALI = ["MATERIALE DI CONSUMO"]


# ============================================
# CATEGORIE SPESE OPERATIVE (NON F&B)
# ============================================
# IMPORTANTE: Queste sono le UNICHE 3 categorie NON considerate Food & Beverage
# TUTTO IL RESTO Ã¨ F&B (incluso MATERIALE DI CONSUMO = materiali consumo ristorante!)
CATEGORIE_SPESE_OPERATIVE = [
    "SERVIZI E CONSULENZE",        # Es: Consulenze HACCP, Commercialista
    "UTENZE E LOCALI",              # Es: Bollette ENEL, Affitto locale
    "MANUTENZIONE E ATTREZZATURE"  # Es: Riparazione forno, Manutenzione cappa
]


# ============================================
# TUTTE LE CATEGORIE (per AI e retrocompatibilitÃ )
# ============================================
# NOTA: Queste liste statiche sono mantenute per retrocompatibilitÃ 
# L'app usa carica_categorie_da_db() per dropdown e UI
TUTTE_LE_CATEGORIE = CATEGORIE_FOOD_BEVERAGE + CATEGORIE_MATERIALI + CATEGORIE_SPESE_OPERATIVE


# RetrocompatibilitÃ  con codice esistente
CATEGORIE_FOOD = CATEGORIE_FOOD_BEVERAGE + CATEGORIE_MATERIALI
CATEGORIE_SPESE_GENERALI = CATEGORIE_SPESE_OPERATIVE


# ============================================
# FORNITORI SPESE GENERALI (utenze, telecom, tech)
# ============================================
# Lista unificata di fornitori che sono SEMPRE spese generali/utenze
# NON confondere con MATERIALE DI CONSUMO (pellicole, guanti, detersivi)
# Questi sono fornitori di SERVIZI, non di prodotti
FORNITORI_SPESE_GENERALI_KEYWORDS = [
    'TIM', 'TELECOM', 'VODAFONE', 'WIND', 'ILIAD', 'FASTWEB',
    'ENEL', 'ENI', 'A2A', 'EDISON', 'CP S.P.A', 'CP SPA',
    'AMAZON', 'MEDIAWORLD', 'UNIEURO', 'LEROY MERLIN',
    'BANCA', 'ASSICURAZ', 'POSTALE', 'POSTE ITALIANE', 'GOOGLE'
]


# ============================================
# REGOLE CATEGORIZZAZIONE PER FORNITORE
# ============================================
# Fornitore specifico → Categoria automatica (priorità ALTA)
# Applicate PRIMA del dizionario keyword
CATEGORIA_PER_FORNITORE = {
    "CP S.P.A": "UTENZE E LOCALI",          # Bollette energia/gas
    "M&M SRL": "GELATI",                    # Fornitore gelati
}


# ============================================
# REGOLE CATEGORIZZAZIONE PER UNITÀ DI MISURA
# ============================================
# Unità misura → Categoria automatica (priorità ALTA)
# Applicate PRIMA del dizionario keyword
UNITA_MISURA_CATEGORIA = {
    "KWH": "UTENZE E LOCALI",     # Kilowattora (energia elettrica)
    "SMC": "UTENZE E LOCALI",     # Standard Metro Cubo (gas)
    "KW": "UTENZE E LOCALI",      # Kilowatt (potenza elettrica)
    "NREE": "UTENZE E LOCALI",    # Numero (quota fissa bollette)
    "GGQFD": "UTENZE E LOCALI",   # Giorni quota fissa distribuzione
}


# ============================================
# DIZIONARIO CORREZIONI INTELLIGENTE
# ============================================
# Mappa keyword â†’ categoria per classificazione rapida
# Usato quando AI non Ã¨ disponibile o per validazione
DIZIONARIO_CORREZIONI = {
    # ===== CARNE =====
    "POLLO": "CARNE",
    "PETTO POLLO": "CARNE",
    "COSCE POLLO": "CARNE",
    "ALI POLLO": "CARNE",
    "MANZO": "CARNE",
    "VITELLO": "CARNE",
    "MAIALE": "CARNE",
    "SUINO": "CARNE",
    "AGNELLO": "CARNE",
    "TACCHINO": "CARNE",
    "CONIGLIO": "CARNE",
    "ANATRA": "CARNE",
    "FESA": "CARNE",
    "COSTATA": "CARNE",
    "BISTECCA": "CARNE",
    "HAMBURGER": "CARNE",
    "SPEZZATINO": "CARNE",
    "ARROSTO": "CARNE",
    "BRASATO": "CARNE",
    "SCALOPPINE": "CARNE",
    
    # ===== PESCE =====
    "SALMONE": "PESCE",
    "TONNO FRESCO": "PESCE",
    "TONNO P.GIALLE": "PESCE",
    "BRANZINO": "PESCE",
    "ORATA": "PESCE",
    "GAMBERI": "PESCE",
    "GAMBERETTI": "PESCE",
    "MAZZANCOLLE": "PESCE",
    "SCAMPI": "PESCE",
    "CALAMARI": "PESCE",
    "POLPO": "PESCE",
    "COZZE": "PESCE",
    "COZZA": "PESCE",
    "VONGOLE": "PESCE",
    "TROTA": "PESCE",
    "SPIGOLA": "PESCE",
    "MERLUZZO": "PESCE",
    "BACCALÃ€": "PESCE",
    "SOGLIOLA": "PESCE",
    "PESCE SPADA": "PESCE",
    "ACCIUGHE": "PESCE",
    "ALICI": "PESCE",
    "SARDINE": "PESCE",
    "PANGASIO": "PESCE",
    "TOTANO": "PESCE",
    "CALAMARO": "PESCE",
    "SEPPIA": "PESCE",
    "GRANCHIO": "PESCE",
    "ARAGOSTA": "PESCE",
    "ASTICE": "PESCE",
    "TENTACOLI": "PESCE",
    "CHELE": "PESCE",
    "CODE GAMBERO": "PESCE",
    "GAMBERONE": "PESCE",
    "GAMBERONI": "PESCE",
    "IMITAZIONE": "PESCE",
    "SURIMI": "PESCE",
    "LYCHEES": "FRUTTA",
    "LITCHI": "FRUTTA",
    "ARBUTUS": "FRUTTA",
    "CORBEZZOLO": "FRUTTA",
    "SCIROPPATO": "FRUTTA",
    "SCIROPPATA": "FRUTTA",
    
    # ===== LATTICINI =====
    "GRANA PADANO": "LATTICINI",
    "PARMIGIANO": "LATTICINI",
    "PECORINO": "LATTICINI",
    "GORGONZOLA": "LATTICINI",
    "TALEGGIO": "LATTICINI",
    "PROVOLONE": "LATTICINI",
    "ASIAGO": "LATTICINI",
    "FONTINA": "LATTICINI",
    "STRACCHINO": "LATTICINI",
    "EMMENTAL": "LATTICINI",
    "MOZZARELLA": "LATTICINI",
    "BURRATA": "LATTICINI",
    "RICOTTA": "LATTICINI",
    "MASCARPONE": "LATTICINI",
    "LATTE": "LATTICINI",
    "PANNA": "LATTICINI",
    "MOZZARELLE PANATE": "LATTICINI",
    "TOFU": "LATTICINI",
    "YOGURT": "LATTICINI",
    "EDAMER": "LATTICINI",
    "PIZZA JULIENNE": "LATTICINI",
    
    # ===== SALUMI =====
    "PROSCIUTTO": "SALUMI",
    "CRUDO": "SALUMI",
    "COTTO": "SALUMI",
    "SALAME": "SALUMI",
    "MORTADELLA": "SALUMI",
    "PANCETTA": "SALUMI",
    "SPECK": "SALUMI",
    "BRESAOLA": "SALUMI",
    # NOTA: "COPPA" spostata in sezione GELATI (COPPA = gelato). Per salumi usare "COPPA DI TESTA" o simili
    "COPPA DI TESTA": "SALUMI",
    "LARDO": "SALUMI",
    "GUANCIALE": "SALUMI",
    # âœ… Richiesta: SALSICCIA e varianti â†’ CARNE (non SALUMI)
    # NOTA: Deve stare PRIMA di VASCHETTA nel dizionario (sorted by length)
    "SALSICCIA": "CARNE",
    "SALSICCE": "CARNE",
    "SALSICCINA": "CARNE",
    "SALSICCINE": "CARNE",
    "SALSICC": "CARNE",
    "SALSIC": "CARNE",
    "WURSTEL": "SALUMI",
    "WÃœRSTEL": "SALUMI",
    
    # ===== UOVA =====
    "UOVA": "UOVA",
    "UOVO": "UOVA",
    
    # ===== VERDURE =====
    "CONTORNO": "VERDURE",
    "POMODORO": "VERDURE",
    "POMODORI": "VERDURE",
    "POMO": "VERDURE",
    "POMO GRAPP": "VERDURE",
    "POMODORO GRAPPOLO": "VERDURE",
    "POMODORI GRAPPOLO": "VERDURE",
    "INSALATA": "VERDURE",
    "LATTUGA": "VERDURE",
    "RUCOLA": "VERDURE",
    "CAROTE": "VERDURE",
    "ZUCCHINE": "VERDURE",
    "MELANZANE": "VERDURE",
    "PEPERONI": "VERDURE",
    "PATATE": "VERDURE",
    "CIPOLLE": "VERDURE",
    "SEDANO": "VERDURE",
    "FINOCCHI": "VERDURE",
    "SPINACI": "VERDURE",
    "BROCCOLI": "VERDURE",
    "CAVOLFIORE": "VERDURE",
    "ASPARAGI": "VERDURE",
    "FUNGHI": "VERDURE",
    "RADICCHIO": "VERDURE",
    "BASILICO": "VERDURE",
    "PREZZEMOLO": "VERDURE",
    "CARCIOFI": "VERDURE",
    "MISTICANZA": "VERDURE",
    
    # ===== FRUTTA =====
    "MELE": "FRUTTA",
    "ARANCIA": "FRUTTA",
    "ARANCE": "FRUTTA",
    "BANANA": "FRUTTA",
    "BANANE": "FRUTTA",
    "FRAGOLE": "FRUTTA",
    "LIMONE": "FRUTTA",
    "LIMONI": "FRUTTA",
    "PERA": "FRUTTA",
    "PERE": "FRUTTA",
    "PESCA": "FRUTTA",
    "PESCHE": "FRUTTA",
    "ALBICOCCHE": "FRUTTA",
    "UVA": "FRUTTA",
    "MELONE": "FRUTTA",
    "ANGURIA": "FRUTTA",
    "KIWI": "FRUTTA",
    "ANANAS": "FRUTTA",
    "MANGO": "FRUTTA",
    "AVOCADO": "FRUTTA",
    
    # ===== PRODOTTI DA FORNO =====
    "PANE": "PRODOTTI DA FORNO",
    "FOCACCIA": "PRODOTTI DA FORNO",
    "GRISSINI": "PRODOTTI DA FORNO",

    "PIZZETTA": "PRODOTTI DA FORNO",
    "CIABATTA": "PRODOTTI DA FORNO",
    "FRANCESINO": "PRODOTTI DA FORNO",
    "MICHETTA": "PRODOTTI DA FORNO",
    "BAGUETTE": "PRODOTTI DA FORNO",
    "PANINI": "PRODOTTI DA FORNO",
    "BASE PIZZA": "PRODOTTI DA FORNO",
    "FOCACCINA": "PRODOTTI DA FORNO",
    "BRIOCHE": "PRODOTTI DA FORNO",
    "CROISSANT": "PRODOTTI DA FORNO",
    
    # ===== SECCO (PASTA, RISO, FARINE) =====
    "PASTA": "SECCO",
    "SPAGHETTI": "SECCO",
    "PENNE": "SECCO",
    "FUSILLI": "SECCO",
    "RIGATONI": "SECCO",
    "TORTIGLIONI": "SECCO",
    "FARFALLE": "SECCO",
    "LINGUINE": "SECCO",
    "TAGLIATELLE": "SECCO",
    "LASAGNE": "SECCO",
    "RAVIOLI": "SECCO",
    "TORTELLINI": "SECCO",
    "TORTELLONI": "SECCO",
    "AGNOLOTTI": "SECCO",
    "CAPPELLETTI": "SECCO",
    "GNOCCHI": "SECCO",
    "CANNELLONI": "SECCO",
    "ORECCHIETTE": "SECCO",
    "TROFIE": "SECCO",
    "PACCHERI": "SECCO",
    "BUCATINI": "SECCO",
    "RISO": "SECCO",
    "FARINA": "SECCO",
    "ZUCCHERO": "SECCO",
    "ROUX": "SECCO",
    "CEREALI": "SECCO",
    "BISCOTTI": "SECCO",
    "FETTE BISCOTTATE": "SECCO",
    
    # ===== OLIO E CONDIMENTI =====
    "OLIO": "OLIO E CONDIMENTI",
    "OLIO OLIVA": "OLIO E CONDIMENTI",
    "OLIO EVO": "OLIO E CONDIMENTI",
    "OLIO EXTRAVERGINE": "OLIO E CONDIMENTI",
    "ACETO": "OLIO E CONDIMENTI",
    "ACETO BALSAMICO": "OLIO E CONDIMENTI",
    "ACETO VINO": "OLIO E CONDIMENTI",
    
    # ===== SPEZIE E AROMI =====
    "PEPE": "SPEZIE E AROMI",
    "PEPERONCINO": "SPEZIE E AROMI",
    "ORIGANO": "SPEZIE E AROMI",
    "ROSMARINO": "SPEZIE E AROMI",
    "SALVIA": "SPEZIE E AROMI",
    "TIMO": "SPEZIE E AROMI",
    "ALLORO": "SPEZIE E AROMI",
    "CURRY": "SPEZIE E AROMI",
    "ZAFFERANO": "SPEZIE E AROMI",
    "CANNELLA": "SPEZIE E AROMI",
    "NOCE MOSCATA": "SPEZIE E AROMI",
    
    # ===== SALSE E CREME =====
    "CREMA PISTACCHIO": "SALSE E CREME",
    "CREMA NOCCIOLA": "SALSE E CREME",
    "PESTO": "SALSE E CREME",
    "KETCHUP": "SALSE E CREME",
    "MAIONESE": "SALSE E CREME",
    "SENAPE": "SALSE E CREME",
    "SAUCE": "SALSE E CREME",
    
    # ===== PROBLEMI AI: Aggiunti al dizionario =====
    # Prodotti che l'AI non riesce a classificare correttamente
    "MIXYBAR": "BEVANDE",
    "FABBRI": "BEVANDE",
    "GRANATINA": "BEVANDE",
    "SCHWEPPES": "BEVANDE",
    "CRODINO": "BEVANDE",
    "HENDRICKS": "DISTILLATI",
    "HENDRICK": "DISTILLATI",
    "DOLCIFICANTE": "VARIE BAR",
    "RISTORA": "VARIE BAR",
    "SERVIZIO DI PRODUZIONE": "SERVIZI E CONSULENZE",
    "INVIO FATTURA": "SERVIZI E CONSULENZE",
    "MUSICA D'AMBIENTE": "SERVIZI E CONSULENZE",
    "APPARECCHIO RADIORIC": "SERVIZI E CONSULENZE",
    "SPESE SPEDIZIONE": "SERVIZI E CONSULENZE",
    "ANTICIPI": "SERVIZI E CONSULENZE",
    "BOLLI": "SERVIZI E CONSULENZE",
    "SPESE BANCARIE": "SERVIZI E CONSULENZE",
    "COMMISSIONI": "SERVIZI E CONSULENZE",
    "RAGÃ™": "SALSE E CREME",
    "SUGO": "SALSE E CREME",
    "BESCIAMELLA": "SALSE E CREME",
    "SALSA": "SALSE E CREME",
    
    # ===== CONSERVE (include scatolame, marmellate, sott'olio) =====
    # Scatolame
    "PELATI": "SCATOLAME E CONSERVE",
    "POMODORI PELATI": "SCATOLAME E CONSERVE",
    "LEGUMI": "SCATOLAME E CONSERVE",
    "FAGIOLI": "SCATOLAME E CONSERVE",
    "CECI": "SCATOLAME E CONSERVE",
    "LENTICCHIE": "SCATOLAME E CONSERVE",
    "TONNO SCATOLA": "SCATOLAME E CONSERVE",
    "TONNO": "SCATOLAME E CONSERVE",
    "MAIS": "SCATOLAME E CONSERVE",
    "PISELLI": "SCATOLAME E CONSERVE",
    # Conserve/Marmellate
    "CONSERVA": "SCATOLAME E CONSERVE",
    "CONSERVE": "SCATOLAME E CONSERVE",
    "MARMELLATA": "SCATOLAME E CONSERVE",
    "CONFETTURA": "SCATOLAME E CONSERVE",
    "COMPOSTA": "SCATOLAME E CONSERVE",
    "GELATINA": "SCATOLAME E CONSERVE",
    "SOTT'OLIO": "SCATOLAME E CONSERVE",
    "SOTTACETO": "SCATOLAME E CONSERVE",
    "SOTTACETI": "SCATOLAME E CONSERVE",
    "OLIVE": "SCATOLAME E CONSERVE",
    "CAPPERI": "SCATOLAME E CONSERVE",
    "CETRIOLINI": "SCATOLAME E CONSERVE",
    "GIARDINIERA": "SCATOLAME E CONSERVE",
    
    # ===== CAFFE E THE =====
    "CAFFÃˆ": "CAFFE E THE",
    "CAFFE": "CAFFE E THE",
    "CAFFE'": "CAFFE E THE",
    "ESPRESSO": "CAFFE E THE",
    "CAPSULE": "CAFFE E THE",
    "CIALDE": "CAFFE E THE",
    "THE": "CAFFE E THE",
    "TÃˆ": "CAFFE E THE",
    "TISANA": "CAFFE E THE",
    "TISANE": "CAFFE E THE",
    "INFUSO": "CAFFE E THE",
    "DECAFFEINATO": "CAFFE E THE",
    "DECA": "CAFFE E THE",
    "DECAF": "CAFFE E THE",
    "CAMOMILLA": "CAFFE E THE",
    "CAMOMILLE": "CAFFE E THE",
    
    # ===== ACQUA =====
    "ACQUA": "ACQUA",
    "FRIZZANTE": "ACQUA",
    "EFFERVESCENTE": "ACQUA",
    
    # ===== BEVANDE =====
    "COCA": "BEVANDE",
    "ARANCIATA": "BEVANDE",
    "LIMONATA": "BEVANDE",
    "THE FREDDO": "BEVANDE",
    "SUCCO": "BEVANDE",
    "DERBY SUCCO": "BEVANDE",
    "ESTATHE": "BEVANDE",
    "SPREMUTA": "BEVANDE",
    "BIBITA": "BEVANDE",
    "CHINOTTO": "BEVANDE",
    "GASSOSA": "BEVANDE",
    
    # ===== VINI =====
    "VINO": "VINI",
    "PROSECCO": "VINI",
    "SPUMANTE": "VINI",
    "LAMBRUSCO": "VINI",
    "CHIANTI": "VINI",
    "BAROLO": "VINI",
    "BARBARESCO": "VINI",
    
    # ===== BIRRE =====
    "BIRRA": "BIRRE",
    "LAGER": "BIRRE",
    "WEISS": "BIRRE",
    "STOUT": "BIRRE",
    
    # ===== DISTILLATI =====
    "VODKA": "DISTILLATI",
    "WHISKY": "DISTILLATI",
    "WHISKEY": "DISTILLATI",
    "TEQUILA": "DISTILLATI",
    "GRAPPA": "DISTILLATI",
    "BRANDY": "DISTILLATI",
    "COGNAC": "DISTILLATI",
    
    # ===== AMARI/LIQUORI =====
    "AMARO": "AMARI/LIQUORI",
    "LIMONCELLO": "AMARI/LIQUORI",
    "SAMBUCA": "AMARI/LIQUORI",
    "AMARETTO": "AMARI/LIQUORI",
    "BAILEYS": "AMARI/LIQUORI",
    "LIQUORE": "AMARI/LIQUORI",
    "DIGESTIVO": "AMARI/LIQUORI",
    
    # ===== PASTICCERIA =====
    "TORTA": "PASTICCERIA",
    "DOLCE": "PASTICCERIA",
    "CROSTATA": "PASTICCERIA",
    "TIRAMISÃ™": "PASTICCERIA",
    "PANNA COTTA": "PASTICCERIA",
    "MOUSSE": "PASTICCERIA",
    "CHEESECAKE": "PASTICCERIA",
    "MILLEFOGLIE": "PASTICCERIA",
    "CANNOLI": "PASTICCERIA",
    "PROFITEROLES": "PASTICCERIA",
    "BIGNÃˆ": "PASTICCERIA",
    "ARAGOSTELLE": "PASTICCERIA",  # Dolci a forma di aragosta (con pistacchio/cioccolato)
    "TARTUFI": "PASTICCERIA",  # Default per dolci (se Ã¨ tartufo vero, viene sovrascritto da admin)
    "SACHER": "PASTICCERIA",
    "NOCCIOL": "PASTICCERIA",
    "MUFFIN": "PASTICCERIA",
    "NUTELLA": "PASTICCERIA",
    "FIAMME": "SHOP",  # Accendini/fiammiferi
    
    # ===== GELATI =====
    "GELATO": "GELATI",
    "GELATI": "GELATI",
    "SORBETTO": "GELATI",
    "COPPA GELATO": "GELATI",
    "COPPA": "GELATI",  # Coppa gelato (anche senza "GELATO" nel testo)
    "CONO": "GELATI",
    "SEMIFREDDO": "GELATI",
    
    # ===== SHOP (prodotti di compravendita senza produzione) =====
    "CICCHE": "SHOP",
    "SIGARETTE": "SHOP",
    "TABACCHI": "SHOP",
    "CARAMELLE": "SHOP",
    "GOMME": "SHOP",
    "GOMMA": "SHOP",
    "CHEWING GUM": "SHOP",
    "PATATINE": "SHOP",
    "CHIPS": "SHOP",
    "SNACK": "SHOP",
    "GOLIA": "SHOP",
    "MENTINE": "SHOP",
    "CARAMELLA": "SHOP",
    "LECCA LECCA": "SHOP",
    "LOLLIPOP": "SHOP",
    "BARRETTE": "SHOP",
    "BARRETTA": "SHOP",
    "CIOCCOLATINI": "SHOP",
    "OVETTI": "SHOP",
    "KINDER": "SHOP",
    "MARS": "SHOP",
    "SNICKERS": "SHOP",
    "TWIX": "SHOP",
    "BOUNTY": "SHOP",
    "CIOCCOLATO CONFEZIONATO": "SHOP",
    
    # ===== VARIE BAR (solo prodotti commestibili per servizio bar) =====
    "GHIACCIO": "VARIE BAR",
    "ZUCCHERO BAR": "VARIE BAR",
    
    # ===== MATERIALI CONSUMO -> MATERIALE DI CONSUMO =====
    "BUSTINE": "MATERIALE DI CONSUMO",
    "PALETTE": "MATERIALE DI CONSUMO",
    "CANNUCCE": "MATERIALE DI CONSUMO",
    "TOVAGLIETTE": "MATERIALE DI CONSUMO",
    "VASCHETTA": "MATERIALE DI CONSUMO",
    "VASCHETTE": "MATERIALE DI CONSUMO",
    "VASCHETTINA": "MATERIALE DI CONSUMO",
    "COPPETTA": "MATERIALE DI CONSUMO",
    "COPPETTE": "MATERIALE DI CONSUMO",
    # NOTA: COPPA GELATO già definita nella sezione GELATI principale
    "TOVAGLIOLO": "MATERIALE DI CONSUMO",
    "TOVAGLIOLI": "MATERIALE DI CONSUMO",
    "TOVAGLIOLIN": "MATERIALE DI CONSUMO",
    "PIATTI": "MATERIALE DI CONSUMO",
    "PIATTO": "MATERIALE DI CONSUMO",
    "PIATTINO": "MATERIALE DI CONSUMO",
    "BICCHIERI": "MATERIALE DI CONSUMO",
    "BICCHIERE": "MATERIALE DI CONSUMO",
    "BICCHIERINO": "MATERIALE DI CONSUMO",
    "CALICE": "MATERIALE DI CONSUMO",
    "POSATE": "MATERIALE DI CONSUMO",
    "FORCHETTA": "MATERIALE DI CONSUMO",
    "FORCHETTE": "MATERIALE DI CONSUMO",
    "CUCCHIAIO": "MATERIALE DI CONSUMO",
    "CUCCHIAI": "MATERIALE DI CONSUMO",
    "CUCCHIAINO": "MATERIALE DI CONSUMO",
    "COLTELLO PLASTICA": "MATERIALE DI CONSUMO",
    "POSATE LEGNO": "MATERIALE DI CONSUMO",
    "POSATE PLASTICA": "MATERIALE DI CONSUMO",
    "CANNUCCIA": "MATERIALE DI CONSUMO",
    "SAC A POCHE": "MATERIALE DI CONSUMO",
    "CARTA": "MATERIALE DI CONSUMO",
    "CARTA FORNO": "MATERIALE DI CONSUMO",
    "CARTA ASSORBENTE": "MATERIALE DI CONSUMO",
    "ROTOLO": "MATERIALE DI CONSUMO",
    "ROTOLI CUCINA": "MATERIALE DI CONSUMO",
    "SCOTTEX": "MATERIALE DI CONSUMO",
    "SACCHETTI": "MATERIALE DI CONSUMO",
    "SACCHETTO": "MATERIALE DI CONSUMO",
    "SHOPPER": "MATERIALE DI CONSUMO",
    "BUSTE": "MATERIALE DI CONSUMO",
    "BUSTA": "MATERIALE DI CONSUMO",
    "CONTENITORI": "MATERIALE DI CONSUMO",
    "CONTENITORE": "MATERIALE DI CONSUMO",
    "ASPORTO": "MATERIALE DI CONSUMO",
    "TAKE AWAY": "MATERIALE DI CONSUMO",
    "COPERCHIO": "MATERIALE DI CONSUMO",
    "COPERCHI": "MATERIALE DI CONSUMO",
    "PELLICOLA": "MATERIALE DI CONSUMO",
    "FILM": "MATERIALE DI CONSUMO",
    "ALLUMINIO": "MATERIALE DI CONSUMO",
    "STAGNOLA": "MATERIALE DI CONSUMO",
    "DETERGENTE": "MATERIALE DI CONSUMO",
    "DETERSIVO": "MATERIALE DI CONSUMO",
    "SGRASSATORE": "MATERIALE DI CONSUMO",
    "SAPONE": "MATERIALE DI CONSUMO",
    "DISINFETTANTE": "MATERIALE DI CONSUMO",
    "IGIENIZZANTE": "MATERIALE DI CONSUMO",
    "GEL MANI": "MATERIALE DI CONSUMO",
    "GUANTI": "MATERIALE DI CONSUMO",
    "GUANTO": "MATERIALE DI CONSUMO",
    "SPUGNA": "MATERIALE DI CONSUMO",
    "SPUGNE": "MATERIALE DI CONSUMO",
    "STROFINACCIO": "MATERIALE DI CONSUMO",
    "STROFINACCI": "MATERIALE DI CONSUMO",
    "PANNO": "MATERIALE DI CONSUMO",
    "PANNI": "MATERIALE DI CONSUMO",
    "STRACCIO": "MATERIALE DI CONSUMO",
    "SCOPA": "MATERIALE DI CONSUMO",
    "MOCIO": "MATERIALE DI CONSUMO",
    "SPAZZOLONE": "MATERIALE DI CONSUMO",
    "TOVAGLIA": "MATERIALE DI CONSUMO",
    "TOVAGLIE": "MATERIALE DI CONSUMO",
    "TAZZA": "MATERIALE DI CONSUMO",
    "TAZZINA": "MATERIALE DI CONSUMO",
    "POMPETTA": "MATERIALE DI CONSUMO",
    "DOSATORE": "MATERIALE DI CONSUMO",
    "TAPPO": "MATERIALE DI CONSUMO",
    "TAPPI": "MATERIALE DI CONSUMO",
    "SCOTCH": "MATERIALE DI CONSUMO",
    "NASTRO ADESIVO": "MATERIALE DI CONSUMO",
    "ETICHETTE": "MATERIALE DI CONSUMO",
    "ETICHETTA": "MATERIALE DI CONSUMO",
    "ETICHETTE ADESIVE": "MATERIALE DI CONSUMO",
    "SPAGO": "MATERIALE DI CONSUMO",
    "ELASTICI": "MATERIALE DI CONSUMO",
    "ELASTICO": "MATERIALE DI CONSUMO",
    "PENNARELLO": "MATERIALE DI CONSUMO",
    "PENNARELLI": "MATERIALE DI CONSUMO",
    "MARKER": "MATERIALE DI CONSUMO",
    "PACKAGING": "MATERIALE DI CONSUMO",
    "TAZZE": "MATERIALE DI CONSUMO",
    "PIATTINI": "MATERIALE DI CONSUMO",
    "COPERTI": "MATERIALE DI CONSUMO",
    "STOVIGLIE": "MATERIALE DI CONSUMO",
    
    # ===== SERVIZI E CONSULENZE =====
    "GOOGLE WORKSPACE": "SERVIZI E CONSULENZE",
    "WORKSPACE": "SERVIZI E CONSULENZE",
    "CANONE": "SERVIZI E CONSULENZE",
    "CONTRIBUTO ATTIVAZIONE": "SERVIZI E CONSULENZE",
    "DIRITTI": "SERVIZI E CONSULENZE",
    "RICAMO": "SERVIZI E CONSULENZE",
    "CONSULENZA": "SERVIZI E CONSULENZE",
    "COMMERCIALISTA": "SERVIZI E CONSULENZE",
    "CONTABILITÃ€": "SERVIZI E CONSULENZE",
    "CONTABILE": "SERVIZI E CONSULENZE",
    "CONSULENTE FISCALE": "SERVIZI E CONSULENZE",
    "FISCALE": "SERVIZI E CONSULENZE",
    "FATTURAZIONE ELETTRONICA": "SERVIZI E CONSULENZE",
    "PUBBLICITÃ€": "SERVIZI E CONSULENZE",
    "MARKETING": "SERVIZI E CONSULENZE",
    "SOCIAL MEDIA": "SERVIZI E CONSULENZE",
    "PUBBLICITA": "SERVIZI E CONSULENZE",
    "POS": "SERVIZI E CONSULENZE",
    # NOTA: "COMMISSIONI" già definita sopra (sezione PROBLEMI AI)
    "COMMISSIONE BANCARIA": "SERVIZI E CONSULENZE",
    "BONIFICO": "SERVIZI E CONSULENZE",
    "ASSICURAZIONE": "SERVIZI E CONSULENZE",
    "POLIZZA": "SERVIZI E CONSULENZE",
    "SOFTWARE": "SERVIZI E CONSULENZE",
    "GESTIONALE": "SERVIZI E CONSULENZE",
    "ABBONAMENTO": "SERVIZI E CONSULENZE",
    "SMALTIMENTO": "SERVIZI E CONSULENZE",
    "RIFIUTI": "SERVIZI E CONSULENZE",
    "HACCP": "SERVIZI E CONSULENZE",
    "CERTIFICAZIONE": "SERVIZI E CONSULENZE",
    "BONUS INTERNET": "SERVIZI E CONSULENZE",
    "BONUS LINEA": "SERVIZI E CONSULENZE",
    "PROMO VALORE": "SERVIZI E CONSULENZE",
    "NUMERI MOBILI": "SERVIZI E CONSULENZE",
    "RICAVI": "SERVIZI E CONSULENZE",
    "ALTRI IMPORTI": "SERVIZI E CONSULENZE",
    "FORMAZIONE": "SERVIZI E CONSULENZE",
    "CORSO": "SERVIZI E CONSULENZE",
    
    # ===== PENALI E INTERESSI =====
    "INDENNITA": "SERVIZI E CONSULENZE",
    "INDENNITÃ€": "SERVIZI E CONSULENZE",
    "MORA": "SERVIZI E CONSULENZE",
    "RITARDATO PAGAMENTO": "SERVIZI E CONSULENZE",
    "INTERESSI": "SERVIZI E CONSULENZE",
    
    # ===== DESCRIZIONI GENERICHE =====
    "SERVIZIO": "SERVIZI E CONSULENZE",
    "OFFERTA": "MANUTENZIONE E ATTREZZATURE",
    "REGISTRAZIONE": "MANUTENZIONE E ATTREZZATURE",
    
    # ===== UTENZE E LOCALI =====
    "ENERGIA ELETTRICA": "UTENZE E LOCALI",
    "RETE ELETTRICA": "UTENZE E LOCALI",
    "ONERI DI SISTEMA": "UTENZE E LOCALI",
    "SPESA PER LA VENDITA": "UTENZE E LOCALI",
    "SPESA PER LA TARIFFA": "UTENZE E LOCALI",
    "LUCE": "UTENZE E LOCALI",
    "ELETTRICITÃ€": "UTENZE E LOCALI",
    "GAS": "UTENZE E LOCALI",
    "METANO": "UTENZE E LOCALI",
    "GPL": "UTENZE E LOCALI",
    "LOCAZIONE": "UTENZE E LOCALI",
    "AFFITTO": "UTENZE E LOCALI",
    "CANONE LOCAZIONE": "UTENZE E LOCALI",
    "CONDOMINIO": "UTENZE E LOCALI",
    "IMU": "UTENZE E LOCALI",
    "TARI": "UTENZE E LOCALI",
    "TASSE": "UTENZE E LOCALI",
    "IMPOSTA": "UTENZE E LOCALI",
    "TELEFONO": "UTENZE E LOCALI",
    "TELECOM": "UTENZE E LOCALI",
    "TIM": "UTENZE E LOCALI",
    "VODAFONE": "UTENZE E LOCALI",
    "WIND": "UTENZE E LOCALI",
    "ILIAD": "UTENZE E LOCALI",
    "FASTWEB": "UTENZE E LOCALI",
    "INTERNET": "UTENZE E LOCALI",
    "ADSL": "UTENZE E LOCALI",
    "FIBRA": "UTENZE E LOCALI",
    "SUPERFIBRA": "UTENZE E LOCALI",
    "TUTTOFIBRA": "UTENZE E LOCALI",
    "TIM GUARDIAN": "UTENZE E LOCALI",
    "5G POWER": "UTENZE E LOCALI",
    "RISCALDAMENTO": "UTENZE E LOCALI",
    "CLIMATIZZAZIONE": "UTENZE E LOCALI",
    "TOTALE IMPOSTE": "UTENZE E LOCALI",
    "ARROTONDAMENTO": "UTENZE E LOCALI",
    # Bollette energia/gas - voci dettagliate
    "SPREAD": "UTENZE E LOCALI",
    "QUOTA FISSA": "UTENZE E LOCALI",
    "QUOTA ENERGIA": "UTENZE E LOCALI",
    "QUOTA TRASPORTO": "UTENZE E LOCALI",
    "QUOTA POTENZA": "UTENZE E LOCALI",
    "QUOTA VARIABILE": "UTENZE E LOCALI",
    "CORRISPETTIVO": "UTENZE E LOCALI",
    "COMPONENTE": "UTENZE E LOCALI",
    "UPLIFT": "UTENZE E LOCALI",
    "DISTRIBUZIONE": "UTENZE E LOCALI",
    "DISPACCIAMENTO": "UTENZE E LOCALI",
    "SBILANCIAMENTO": "UTENZE E LOCALI",
    "ACCISA": "UTENZE E LOCALI",
    "COMMERCIALIZZAZIONE": "UTENZE E LOCALI",
    "ONERI": "UTENZE E LOCALI",
    "ASOS": "UTENZE E LOCALI",
    "ARIM": "UTENZE E LOCALI",
    "SCAGLIONE": "UTENZE E LOCALI",
    "CAPACITA": "UTENZE E LOCALI",
    "CAPACITÀ": "UTENZE E LOCALI",
    "CCR": "UTENZE E LOCALI",
    "MANCATA PRODUZIONE": "UTENZE E LOCALI",
    "COSTI FUNZIONAMENTO TERNA": "UTENZE E LOCALI",
    "PERTITE ECONOMICHE": "UTENZE E LOCALI",
    
    # ===== MANUTENZIONE E ATTREZZATURE =====
    "VASSOIO VETRINA": "MANUTENZIONE E ATTREZZATURE",
    "VASSOIO INOX": "MANUTENZIONE E ATTREZZATURE",
    "CARRELLO": "MANUTENZIONE E ATTREZZATURE",
    "PROLUNGA": "MANUTENZIONE E ATTREZZATURE",
    "RIPARAZIONE": "MANUTENZIONE E ATTREZZATURE",
    "MANUTENZIONE": "MANUTENZIONE E ATTREZZATURE",
    "LIBERATO": "MANUTENZIONE E ATTREZZATURE",
    "RICERCA GUASTO": "MANUTENZIONE E ATTREZZATURE",
    "SOSTITUZIONE": "MANUTENZIONE E ATTREZZATURE",
    "INSTALLAZIONE": "MANUTENZIONE E ATTREZZATURE",
    "UPGRADE": "MANUTENZIONE E ATTREZZATURE",
    "KIT BASE": "MANUTENZIONE E ATTREZZATURE",
    "ZEROVISION": "MANUTENZIONE E ATTREZZATURE",
    "PACK SOS": "MANUTENZIONE E ATTREZZATURE",
    "OFFERTA SCONTO CANONE": "MANUTENZIONE E ATTREZZATURE",
    "FRIGORIFERO": "MANUTENZIONE E ATTREZZATURE",
    "FRIGO": "MANUTENZIONE E ATTREZZATURE",
    "FORNO": "MANUTENZIONE E ATTREZZATURE",
    "LAVASTOVIGLIE": "MANUTENZIONE E ATTREZZATURE",
    "LAVABICCHIERI": "MANUTENZIONE E ATTREZZATURE",
    "IMPIANTO": "MANUTENZIONE E ATTREZZATURE",
    "ELETTRICO": "MANUTENZIONE E ATTREZZATURE",
    "IDRAULICO": "MANUTENZIONE E ATTREZZATURE",
    "CLIMATIZZATORE": "MANUTENZIONE E ATTREZZATURE",
    "CONDIZIONATORE": "MANUTENZIONE E ATTREZZATURE",
    "CAPPA": "MANUTENZIONE E ATTREZZATURE",
    "ASPIRAZIONE": "MANUTENZIONE E ATTREZZATURE",
    "ARREDO": "MANUTENZIONE E ATTREZZATURE",
    "MOBILIO": "MANUTENZIONE E ATTREZZATURE",
    "TAVOLO": "MANUTENZIONE E ATTREZZATURE",
    "SEDIA": "MANUTENZIONE E ATTREZZATURE",
    "ATTREZZATURA": "MANUTENZIONE E ATTREZZATURE",
    "MACCHINA CAFFÃˆ": "MANUTENZIONE E ATTREZZATURE",
    "MACINADOSATORE": "MANUTENZIONE E ATTREZZATURE",
    "MIXER": "MANUTENZIONE E ATTREZZATURE",
    "ROBOT": "MANUTENZIONE E ATTREZZATURE",
    "ABBATTITORE": "MANUTENZIONE E ATTREZZATURE",
    "AFFETTATRICE": "MANUTENZIONE E ATTREZZATURE",
    "BILANCIA": "MANUTENZIONE E ATTREZZATURE",
    "COLTELLO": "MANUTENZIONE E ATTREZZATURE",
    "PENTOLE": "MANUTENZIONE E ATTREZZATURE",
    "PADELLE": "MANUTENZIONE E ATTREZZATURE",
    "UTENSILI": "MANUTENZIONE E ATTREZZATURE",

    
    # ===== GELATI E DESSERT (keywords aggiuntivi, base in sezione GELATI sopra) =====
    # NOTA: GELATO, GELATI, CONO, COPPA GELATO già definiti nella sezione GELATI principale
    "PIRATA": "GELATI",
    "PRINCIPESSA": "GELATI",
    "TARTUFO": "GELATI",
    "SOUFFLE": "GELATI",
    "SOUFFLÉ": "GELATI",
    "MERINGA": "GELATI",
    "CROCCANTE": "GELATI",
    "FR.RI.": "GELATI",
    "FRESCO RIPIENO": "GELATI",
    "COCCO CF": "GELATI",
    "SPAGNOLA CF": "GELATI",
    
    # ===== INGREDIENTI ASIATICI =====
    # NOTA: Ingredienti specifici sushi/decorazione → SUSHI VARIE
    # Salse asiatiche generiche restano in SALSE E CREME
    "NORI": "SUSHI VARIE",
    "YAKI NORI": "SUSHI VARIE",
    "GIKU": "SUSHI VARIE",
    "SUSHI NORI": "SUSHI VARIE",
    "ALGHE": "SUSHI VARIE",
    "ALGA": "SUSHI VARIE",
    "WAKAME": "SUSHI VARIE",
    "KONBU": "SUSHI VARIE",
    "PANKO": "SUSHI VARIE",
    "DASHI": "SPEZIE E AROMI",
    "MISO": "SALSE E CREME",
    "ZENZERO SALAMOIA": "SCATOLAME E CONSERVE",
    "ZENZERO IN SALAMOIA": "SCATOLAME E CONSERVE",
    "SESAMO": "SPEZIE E AROMI",
    "SESAMO NERO": "SPEZIE E AROMI",
    "WASABI": "SUSHI VARIE",
    "TEMPURA": "SUSHI VARIE",
    "EDAMAME": "VERDURE",
    "CIPOLLA FRITTA": "SCATOLAME E CONSERVE",
    "BAMBU": "SUSHI VARIE",
    "BAMBÙ": "SUSHI VARIE",
    "FOGLIE BAMBU": "SUSHI VARIE",
    "FOGLIE DI BAMBU": "SUSHI VARIE",
    "TOBIKO": "SUSHI VARIE",
    "EBIKO": "SUSHI VARIE",
    "MASAGO": "SUSHI VARIE",
    "SUSHI": "SUSHI VARIE",
    "TOPPING SUSHI": "SUSHI VARIE",
    
    # ===== SALSE ASIATICHE =====
    "SAKE CUCINA": "SALSE E CREME",
    "MIRIN": "SALSE E CREME",
    "SAMBAL": "SALSE E CREME",
    "SAMBAL OELEK": "SALSE E CREME",
    "UNAGI": "SALSE E CREME",
    "UNAGI SAUCE": "SALSE E CREME",
    "TERIYAKI": "SALSE E CREME",
    "HAKUTSURU": "SALSE E CREME",
    "MIZKAN": "SALSE E CREME",
    "DRESSING": "SALSE E CREME",
    
    # ===== BEVANDE ASIATICHE =====
    "SPRITE": "BEVANDE",
    "SAPPORO": "BIRRE",
    "ASAHI": "BIRRE",
    "KIRIN": "BIRRE",
    "TSINGTAO": "BIRRE",
    "BIRRA CAN": "BIRRE",
    "SILVER CAN": "BIRRE",
    
    # ===== MATERIALE CONSUMO SPECIFICO =====
    "BASTONCINO BAMBU": "MATERIALE DI CONSUMO",
    "BACCHETTE": "MATERIALE DI CONSUMO",
    "BOBINA": "MATERIALE DI CONSUMO",
    "STRAPI": "MATERIALE DI CONSUMO",
    "STRAPPO": "MATERIALE DI CONSUMO",
    "CONTRIBUTO SPESE": "MATERIALE DI CONSUMO",
    "SPESE CONSEGNA": "MATERIALE DI CONSUMO",
    "SODA": "MATERIALE DI CONSUMO",
    "BICARBONATO": "MATERIALE DI CONSUMO",
    "TACO SHELLS": "SECCO",
    "NUVOLE DI DRAGO": "SECCO",
    "PASTO DI GRANO": "SECCO",
    "WHITE PRAWN CRACKERS": "SECCO",
    "CRACKERS": "SECCO",
    
    # ===== FIX DIZIONARIO CONSERVATIVO - KEYWORD SPECIFICHE =====
    "BISCOTTINI": "PASTICCERIA",
    "CANDEGGINA": "MATERIALE DI CONSUMO",
    "CROSTATE": "PASTICCERIA",
    "CROSTATINE": "PASTICCERIA",
    "DOLCI NATALIZI": "PASTICCERIA",
    "FACCINE": "PASTICCERIA",
    "MIX NATALE": "PASTICCERIA",
    "MOUSSE MANI": "MATERIALE DI CONSUMO",
    "PASSATA POMOD": "SCATOLAME E CONSERVE",
    "PASSATA POMODORO": "SCATOLAME E CONSERVE",
    "SALAME CIOCCOLATO": "PASTICCERIA",
    "SALAME DI CIOCCOLATO": "PASTICCERIA",

# ===== KEYWORDS DAL FIX REPORT ERRORI =====
    "ARAGONOSTINE": "PASTICCERIA",
    "ARAGOSTINE": "PASTICCERIA",
    "BEVANDA DI SOJA": "BEVANDE",
    "BEVANDA SOJA": "BEVANDE",
    "BOLLO SPESA": "SERVIZI E CONSULENZE",
    "BRIE": "LATTICINI",
    "BRILL": "MATERIALE DI CONSUMO",
    "CANES": "PASTICCERIA",
    "CANESTRELLI": "PASTICCERIA",
    "CANESTRELLO": "PASTICCERIA",
    "CANNOLO": "PASTICCERIA",
    "CANNONCINI": "PASTICCERIA",
    "CANNONCINO": "PASTICCERIA",
    "CANNOLI SFOGLIA": "PASTICCERIA",
    "CONCHIGLIA PANNA": "PASTICCERIA",
    # "ARAGOSTINE": duplicato rimosso (giÃ  definito sopra)
    "CAPRA": "LATTICINI",
    "CAPRINO": "LATTICINI",
    "CAPRINO VACCINO": "LATTICINI",
    "CREMA GIANDUIA": "PASTICCERIA",
    "CREMA GIANDUJA": "PASTICCERIA",
    # NOTA: "EDAMAME" già definita sopra (sezione INGREDIENTI ASIATICI)
    "ESSE": "PASTICCERIA",
    "ESSE GIGANTI": "PASTICCERIA",
    "ESSENCE": "PASTICCERIA",
    "FARCITURA": "SALSE E CREME",
    "FARCITURA CACAO": "SALSE E CREME",
    "FROLLA": "PASTICCERIA",
    "FROLLA MISTA": "PASTICCERIA",
    "GENOVESI": "PASTICCERIA",
    "GIANDUIA": "PASTICCERIA",
    "GIANDUJA": "PASTICCERIA",
    "LAVASTOV": "MATERIALE DI CONSUMO",
    "MISTER X": "MATERIALE DI CONSUMO",
    # NOTA: "TAZZA" già definita sopra (sezione MATERIALI CONSUMO)
    "GREMBIULE": "MATERIALE DI CONSUMO",
    "SALE PASTIGLIE": "MATERIALE DI CONSUMO",
    "MISTO FROLLA": "PASTICCERIA",
    "NOCE BOV": "CARNE",
    "NOCE BOVINO": "CARNE",
    "OCCHI BUE": "PASTICCERIA",
    "OCCHI DI BUE": "PASTICCERIA",
    "PARMA": "SALUMI",
    # âœ… PASSATA â†’ SCATOLAME E CONSERVE (unificato, rimossi duplicati da righe 819-821)
    "PASSATA": "SCATOLAME E CONSERVE",
    # "PASSATA POMOD": duplicato rimosso (definito sopra come SALSE E CREME, ora unificato)
    # "PASSATA POMODORO": duplicato rimosso (definito sopra come SALSE E CREME, ora unificato)
    "PANNA SPRAY": "VARIE BAR",
    "ZUCCHERO BUSTINE": "VARIE BAR",
    # NOTA: "ZUCCHERO BAR" già definita sopra (sezione VARIE BAR)
    "PAIN AU CHOCOLAT": "PRODOTTI DA FORNO",
    "EDAMINO": "LATTICINI",
    "RIBOLLA": "VINI",
    "IGT": "VINI",
    "CONGUAGLIO": "SERVIZI E CONSULENZE",
    "CONSUNTIVO": "SERVIZI E CONSULENZE",
    "PIADINA": "PRODOTTI DA FORNO",
    "PIADINE": "PRODOTTI DA FORNO",
    "PREGISAN": "MATERIALE DI CONSUMO",
    "PREMI": "SERVIZI E CONSULENZE",
    "RIF SAN PREGISAN": "MATERIALE DI CONSUMO",
    "SAVOIARDI": "PASTICCERIA",
    "SAVOIARDO": "PASTICCERIA",
    "SICILIANI CANNOLO": "PASTICCERIA",
    "SICILIANO CANNOLO": "PASTICCERIA",
    "SOIA": "BEVANDE",
    "SOJA": "BEVANDE",
    "SPESE DI BOLLO": "SERVIZI E CONSULENZE",
    "STRUDEL": "PASTICCERIA",

}

# ============================================================
# AMMINISTRATORI DI SISTEMA
# ============================================================

# Lista email degli amministratori (fonte unica di verità)
ADMIN_EMAILS = ["mattiadavolio90@gmail.com"]

