-- MODALITÀ CATENA — Fase 4: tag di catena.
--
-- Tag DI GRUPPO, SCOLLEGATI dai tag di sede (custom_tags/custom_tag_prodotti):
-- vivono a livello ACCOUNT (user_id, niente ristorante_id), si applicano a tutti
-- i PV. L'associazione è per descrizione prodotto (descrizione_key), come i tag
-- di sede — l'anagrafica prodotti è già account-wide (stesse descrizioni fra PV).
--
-- + 2 RPC SQL (no full-load, regola catena):
--   gruppo_tag_descrizioni: descrizioni distinte su tutti i PV (per costruire il tag)
--   gruppo_tag_analisi: spesa/quantità/righe per PV per le descrizioni del tag

CREATE TABLE IF NOT EXISTS gruppo_tags (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     uuid        NOT NULL,
    nome        text        NOT NULL,
    emoji       text,
    colore      text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gruppo_tag_prodotti (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id          bigint      NOT NULL REFERENCES gruppo_tags(id) ON DELETE CASCADE,
    user_id         uuid        NOT NULL,
    descrizione     text        NOT NULL,
    descrizione_key text        NOT NULL,
    fattore_kg      numeric,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_gruppo_tags_user ON gruppo_tags (user_id);
CREATE INDEX IF NOT EXISTS idx_gruppo_tag_prodotti_tag ON gruppo_tag_prodotti (tag_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_gruppo_tag_prodotti_unique
    ON gruppo_tag_prodotti (tag_id, descrizione_key);

ALTER TABLE gruppo_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE gruppo_tag_prodotti ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON gruppo_tags TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON gruppo_tag_prodotti TO service_role;
REVOKE ALL ON gruppo_tags FROM anon, authenticated;
REVOKE ALL ON gruppo_tag_prodotti FROM anon, authenticated;

COMMENT ON TABLE gruppo_tags IS
    'Tag di catena (livello account, scollegati dai custom_tags di sede). service_role.';


-- Descrizioni distinte su tutti i PV del gruppo, con conteggio occorrenze, per
-- costruire/estendere un tag di catena. Normalizzazione chiave = identica a
-- _normalize_custom_tag_key (UPPER + collapse whitespace + trim).
CREATE OR REPLACE FUNCTION gruppo_tag_descrizioni(
    p_ristorante_ids uuid[],
    p_limit int DEFAULT 500
)
RETURNS TABLE (descrizione text, descrizione_key text, n bigint, spesa numeric)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        (array_agg(f.descrizione ORDER BY f.data_documento DESC))[1] AS descrizione,
        upper(regexp_replace(btrim(f.descrizione), '\s+', ' ', 'g')) AS descrizione_key,
        count(*)::bigint AS n,
        sum(f.totale_riga) AS spesa
    FROM fatture f
    WHERE f.ristorante_id = ANY(p_ristorante_ids)
      AND f.deleted_at IS NULL
      AND f.categoria <> 'Da Classificare'
      AND f.descrizione IS NOT NULL
      AND btrim(f.descrizione) <> ''
      AND f.prezzo_unitario > 0
    GROUP BY descrizione_key
    ORDER BY spesa DESC NULLS LAST
    LIMIT p_limit;
$$;

REVOKE ALL ON FUNCTION gruppo_tag_descrizioni(uuid[], int) FROM public, anon, authenticated;


-- Analisi macro per PV di un tag di catena: per le descrizioni date, spesa +
-- quantità (grezza) + n righe + n fornitori, GROUP BY ristorante_id. SQL puro.
CREATE OR REPLACE FUNCTION gruppo_tag_analisi(
    p_ristorante_ids uuid[],
    p_descrizione_keys text[],
    p_data_da date,
    p_data_a date
)
RETURNS TABLE (
    ristorante_id uuid,
    spesa numeric,
    quantita numeric,
    n_righe bigint,
    n_fornitori bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        f.ristorante_id,
        sum(f.totale_riga) AS spesa,
        sum(CASE WHEN f.quantita > 0 THEN f.quantita ELSE 0 END) AS quantita,
        count(*)::bigint AS n_righe,
        count(DISTINCT f.fornitore)::bigint AS n_fornitori
    FROM fatture f
    WHERE f.ristorante_id = ANY(p_ristorante_ids)
      AND f.deleted_at IS NULL
      AND f.prezzo_unitario > 0
      AND upper(regexp_replace(btrim(f.descrizione), '\s+', ' ', 'g')) = ANY(p_descrizione_keys)
      AND COALESCE(f.data_competenza, f.data_documento) IS NOT NULL
      AND COALESCE(f.data_competenza, f.data_documento) >= p_data_da
      AND COALESCE(f.data_competenza, f.data_documento) <= p_data_a
    GROUP BY f.ristorante_id;
$$;

REVOKE ALL ON FUNCTION gruppo_tag_analisi(uuid[], text[], date, date) FROM public, anon, authenticated;
